ManagementSystem.UI/Models/ErrorViewModel.cs
namespace ManagementSystem.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ManagementSystem.UI/Controllers/AdminController.cs
using ManagementSystem.Application.Features.Commands.FRole.AssignRole;
using ManagementSystem.Application.Features.Commands.FRole.CreateRole;
using ManagementSystem.Application.Features.Queries.FUser.GetAllUsers;
using ManagementSystem.Application.Features.Queries.FUser.LoginUser;
using ManagementSystem.Domain;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ManagementSystem.UI.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdminController : Controller
    {
        readonly IMediator _mediator;

        public AdminController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole([FromBody] CreateRoleCommandRequest model)
        {
            if (ModelState.IsValid)
            {

                CreateRoleCommandResponse res = await _mediator.Send(model);

                return Json(new { success = res.Success, message = res.Message });
            }

            return Json(new { success = false, message = "Geçersiz Kayıt!" });
        }

        [HttpGet]
        public async Task<IActionResult> AssignRole()
        {
            GetAllUsersQueryResponse response = await _mediator.Send(new GetAllUsersQueryRequest());

            

            ViewData["Users"] = response;
            return View(Json(new { success = false, message = "Buraya geldim", data =" response.Data" }));

        }

        [HttpPost]
        public async Task<IActionResult> AssignRole([FromBody] AssignRoleCommandRequest model)
        {
            if (ModelState.IsValid)
            {

                AssignRoleCommandResponse res = await _mediator.Send(model);

                return Json(new { success = res.Success, message = res.Message });
            }

            return Json(new { success = false, message = "Geçersiz Kayıt!" });
        }
    }
}

ManagementSystem.UI/Controllers/SigninController.cs
using ManagementSystem.Application.Features.Commands.FUser.CreateUser;
using ManagementSystem.Application.Features.Queries.FUser.LoginUser;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace ManagementSystem.UI.Controllers
{
    public class SigninController : Controller
    {
        readonly private IMediator _mediator;

        public SigninController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> _GirisYap([FromBody] LoginUserQueryRequest model)
        {
            if (ModelState.IsValid)
            {

                LoginUserSuccessQueryResponse res = await _mediator.Send(model);

                return Json(new { success = res.Success, message = res.Message, role = res.Role, token = res.Token });
            }


            return Json(new { success = false, message = "Geçersiz giriş!" });
        }

    }
}

ManagementSystem.UI/Controllers/SignupController.cs
using ManagementSystem.Application.Features.Commands.FUser.CreateUser;
using ManagementSystem.Application.Features.Queries.FUser.GetByEmailUser;
 using MediatR;
using Microsoft.AspNetCore.Mvc; 

namespace ManagementSystem.UI.Controllers
{
    public class SignupController : Controller
    {
        readonly private IMediator _mediator;

        public SignupController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> üyeOl([FromBody] CreateUserCommandRequest model)
        {
            if (ModelState.IsValid)
            {
                CreateUserCommandResponse res = await _mediator.Send(model);

                return Json(new { success = res.Success, message = res .Message});
            }

            return Json(new { success = false, message = "Geçersiz giriş!" });
        }




    }
}

ManagementSystem.UI/Controllers/UsersController.cs
using ManagementSystem.Application.Features.Commands.FAppointments.CreateAppointments;
using ManagementSystem.Application.Features.Commands.FRole.CreateRole;
using ManagementSystem.Domain;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ManagementSystem.UI.Controllers
{
    [Authorize(Roles ="User")]
    public class UsersController : Controller
    {
        private readonly IMediator _mediator;
        private readonly UserManager<User> _userManager;
        public UsersController(IMediator mediator, UserManager<User> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            var a = await _userManager.GetUserAsync(HttpContext.User);
            var b = await _userManager.GetRolesAsync(a);

            var userName = HttpContext.User.Identity.Name;
            var role = HttpContext.User.Claims.FirstOrDefault(a=>a.Type== "nebakiyonle")?.Value;

            return View();
        }
         

        [HttpPost]
        public async Task<IActionResult> CreateAppointments([FromBody] CreateAppointmentsCommandRequest model)
        {
            if (ModelState.IsValid)
            {

                CreateAppointmentsCommandResponse res = await _mediator.Send(model);

                return Json(new { success = res.Success, message = res.Message });
            }

            return Json(new { success = false, message = "Geçersiz Kayıt!" });
        }
    }
}

ManagementSystem.UI/Views/Admin/AddRole.cshtml
@{
    ViewData["Title"] = "AddRole";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header align-items-center d-flex">
                    <h4 class="card-title mb-0 flex-grow-1">Rol Yönetim Tanımlamaları </h4>
                </div><!-- end card header -->
                <div class="card-body">
                    <div class="live-preview">
                        <div>
                            <div class="row g-3">

                                <div class="col-lg-6    ">
                                    <div class="input-group">

                                        <label class="form-label">Rol Tanımlama Adı<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" id="RoleName" placeholder="Rol adı giriniz" required="">
                                        <div class="invalid-feedback">
                                            Rol adını giriniz
                                        </div>
                                        <button class="btn btn-outline-success" id="RolKaydet" type="submit">Rol Kaydet</button>

                                    </div>
                                </div>
                                <div class="col-lg-6">

                                    <table class="table table-nowrap">
                                        <thead>
                                            <tr>
                                                <th scope="col">ID</th>
                                                <th scope="col">Role</th> 
                                                <th scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th scope="row"><a href="#" class="fw-semibold">#1</a></th>
                                                <td>Admin</td> 
                                            </tr>
                                            <tr>
                                                <th scope="row"><a href="#" class="fw-semibold">#2</a></th>
                                                <td>User</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>


<script>
    $(document).ready(function () {
        $("#RolKaydet").click(function (event) {
            event.preventDefault();
            var formData = {
                RoleName: $("#RoleName").val()
            };
            $.ajax({
                url: '/Admin/AddRole',
                type: 'post',
                contentType: 'application/json',
                data: JSON.stringify(formData),
                success: function (response) {
                    if (response.success) { 
                        Swal.fire({
                            icon: 'success',
                            title: 'Başarıyla Kaydedildi!',
                            text: response.message,
                            confirmButtonText: 'Tamam'
                        }).then(function() { 
                            window.location.href = '/Admin/AddRole';
                        });
                    } else { 
                        Swal.fire({
                            icon: 'error',
                            title: 'Kayıt Başarısız!',
                            text: response.message,
                            confirmButtonText: 'Tamam'
                        }).then(function() { 
                            window.location.href = '/Admin/AddRole';
                        });
                    }
                },
                error: function () { 
                    Swal.fire({
                        icon: 'error',
                        title: 'Bir Hata Oluştu',
                        text: 'Bir hata oluştu. Lütfen tekrar deneyin.',
                        confirmButtonText: 'Tamam'
                    }).then(function() { 
                        window.location.href = '/Admin/AddRole';
                    });
                }
            });
        });
    });
</script>

ManagementSystem.UI/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
 
<div class="row">
    <div class="col-lg-12">
        <div class="card"> 
            <div class="card-body">
                <div id="customerList">
                    <div class="table-responsive table-card mt-3 mb-1">
                        <table class="table align-middle table-nowrap" id="Appointments" border="1">
                            <thead class="table-light">
                                <tr>
                                    <th class="sort" data-sort="UserName">Müşteri Adı</th>
                                    <th class="sort" data-sort="Email">Email</th>
                                    <th class="sort" data-sort="PhoneNumber">Telefon</th>
                                    <th class="sort" data-sort="Service">Hizmet Bilgisi</th>
                                    <th class="sort" data-sort="Date">Tarih & Saat</th>
                                 </tr>
                            </thead>
                            <tbody class="list form-check-all" id="AppointmentsTableBody">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>

ManagementSystem.UI/Views/CheckAdminUser/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>selam</h1>

ManagementSystem.UI/Views/Signin/Index.cshtml
<html lang="en" data-layout="horizontal" data-layout-style="" data-layout-position="fixed" data-topbar="light">

<head>

    <meta charset="utf-8" />
    <title>Giriş Sayfası</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/velzon/assets/images/favicon.ico">
    <!-- plugin css -->
    <link href="~/velzon/assets/libs/jsvectormap/css/jsvectormap.min.css" rel="stylesheet" type="text/css" />
    <!-- Layout config Js -->
    <script src="~/velzon/assets/js/layout.js"></script>
    <!-- Bootstrap Css -->
    <link href="~/velzon/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="~/velzon/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/velzon/assets/css/app.min.css" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="~/velzon/assets/css/custom.min.css" rel="stylesheet" type="text/css" />

</head>

<body>

    <div class="auth-page-wrapper pt-5">
        <!-- auth page bg -->
        <div class="auth-one-bg-position auth-one-bg" id="auth-particles">
            <div class="bg-overlay"></div>

            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
            <canvas class="particles-js-canvas-el" width="1903" height="380" style="width: 100%; height: 100%;"></canvas>
        </div>

        <!-- auth page content -->
        <div class="auth-page-content">
            <div class="container">
                <!-- end row -->

                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card mt-4">

                            <div class="card-body p-4">
                                <div class="text-center mt-2">
                                    <h5 class="text-primary">Hoş Geldiniz</h5>
                                    <p class="text-muted">Devam Etmek İçin Oturum Açın</p>
                                </div>
                                <div class="p-2 mt-4">
                                    <form class="needs-validation" method="post" action="/" id="LoginForm">

                                        <div class="mb-3">
                                            <label class="form-label">Kullanıcı Adı & EMail<span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" id="UserNameOrMail" placeholder="Kullanıcı adı & mail giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen kullanıcı adınızı giriniz
                                            </div>
                                        </div>

                                        <div class="mb-2">
                                            <label class="form-label">Şifre <span class="text-danger">*</span></label>
                                            <input type="password" class="form-control" id="UserPassword" placeholder="Şifre giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen şifrenizi giriniz
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <button class="btn btn-success w-100" id="GirisYap" type="submit">Giriş Yap</button>
                                        </div>
                                        <div id="responseMessage"></div>


                                    </form>
                                </div>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card -->

                        <div class="mt-4 text-center">
                            <p class="mb-0"> Hesabınız yok mu?  <a class="fw-semibold text-primary text-decoration-underline" asp-controller="Signup" asp-action="Index">Üye Ol</a> </p>
                        </div>

                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
    </div>
    <!-- JAVASCRIPT -->
    <script src="~/velzon/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/velzon/assets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/velzon/assets/libs/node-waves/waves.min.js"></script>
    <script src="~/velzon/assets/libs/feather-icons/feather.min.js"></script>
    <script src="~/velzon/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
    <script src="~/velzon/assets/js/plugins.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <!-- App js -->
    <script src="~/velzon/assets/js/app.js"></script>

    <!-- particles js -->
    <script src="~/velzon/assets/libs/particles.js/particles.js"></script>
    <!-- particles app js -->
    <script src="~/velzon/assets/js/pages/particles.app.js"></script>
    <!-- validation init -->
    <script src="~/velzon/assets/js/pages/form-validation.init.js"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jwt-decode@3.1.2/build/jwt-decode.min.js"></script>



    <script>
        $(document).ready(function () {
            $("#GirisYap").click(function (event) {
                event.preventDefault();
                var formData = {
                    UserNameOrMail: $("#UserNameOrMail").val(),
                    UserPassword: $("#UserPassword").val()
                };
                $.ajax({
                    url: '/Signin/_GirisYap',
                    type: 'post',
                    contentType: 'application/json',
                    data: JSON.stringify(formData),
                    success: function (response) {
                        if (response.success) { 
                            debugger;
                            console.log(response.role)
                            var redirectUrl = response.role === 'Admin' ? '/Admin/Index' : '/Users/Index';
                             Swal.fire({
                                icon: 'success',
                                title: 'Başarıyla Giriş Yapıldı!',
                                text: response.message,
                                confirmButtonText: 'Tamam'
                            }).then(function () {
                                 window.location.href = redirectUrl;
                            });
                        } else { 
                            Swal.fire({
                                icon: 'error',
                                title: 'Giriş Başarısız!',
                                text: response.message,
                                confirmButtonText: 'Tamam'
                            }).then(function () {
                                // Sayfayı yönlendir
                                window.location.href = '/Signin/Index';
                            });
                        }
                    },
                    error: function () { 
                        Swal.fire({
                            icon: 'error',
                            title: 'Bir Hata Oluştu',
                            text: 'Bir hata oluştu. Lütfen tekrar deneyin.',
                            confirmButtonText: 'Tamam'
                        }).then(function () { 
                            window.location.href = '/Signin/Index';
                        });
                    }
                });
            });
        });
    </script>


</body>
</html>

ManagementSystem.UI/Views/Signup/Index.cshtml
<html lang="en" data-layout="horizontal" data-layout-style="" data-layout-position="fixed" data-topbar="light">

<head>

    <meta charset="utf-8" />
    <title>Kullanıcı Oluştur</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <link rel="shortcut icon" href="~/velzon/assets/images/favicon.ico">
    <link href="~/velzon/assets/libs/jsvectormap/css/jsvectormap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/velzon/assets/js/layout.js"></script>
    <link href="~/velzon/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/velzon/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/velzon/assets/css/app.min.css" rel="stylesheet" type="text/css" />
    <link href="~/velzon/assets/css/custom.min.css" rel="stylesheet" type="text/css" />

</head>

<body>

    <div class="auth-page-wrapper pt-5">
        <div class="auth-one-bg-position auth-one-bg" id="auth-particles">
            <div class="bg-overlay"></div>

            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
            <canvas class="particles-js-canvas-el" width="1903" height="380" style="width: 100%; height: 100%;"></canvas>
        </div>

        <div class="auth-page-content">
            <div class="container">

                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card mt-4">

                            <div class="card-body p-4">
                                <div class="text-center mt-2">
                                    <h5 class="text-primary">Yeni Hesap Oluştur</h5>
                                    <p class="text-muted">Ücretsiz hesabınızı hemen alın</p>
                                </div>
                                <div class="p-2 mt-4">
                                    <form class="needs-validation" method="post" action="/" id="CreateForm">

                                        <div class="mb-3">
                                            <label for="useremail" class="form-label">Email <span class="text-danger">*</span></label>
                                            <input type="email" class="form-control" id="UserEmail" placeholder="Mail adresi giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen Mail adresi giriniz
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            <label for="username" class="form-label">Kullanıcı Adı <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" id="UserName" placeholder="Kullanıcı adınızı giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen kullanıcı adınızı giriniz
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            <label for="username" class="form-label">Telefon Numarası <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" id="PhoneNumber" placeholder="Telefon Numaranızı giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen Telefon Numaranızı giriniz
                                            </div>
                                        </div>

                                        <div class="mb-2">
                                            <label for="userpassword" class="form-label">Şifre <span class="text-danger">*</span></label>
                                            <input type="password" class="form-control" id="UserPassword" placeholder="Şifre giriniz" required="">
                                            <div class="invalid-feedback">
                                                Lütfen şifrenizi giriniz
                                            </div>
                                        </div>

                                        <div class="mt-4">
                                            <button class="btn btn-success w-100" id="üye_ol" type="submit">Üye ol</button>
                                        </div>
                                        <div id="responseMessage"></div>

                                    </form>

                                </div>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card -->

                        <div class="mt-4 text-center">
                            <p class="mb-0">
                                Zaten bir hesabınız var mı?
                                <a class="fw-semibold text-primary text-decoration-underline" asp-area="" asp-controller="Signin" asp-action="Index">Giriş Yap</a>
                            </p>
                        </div>

                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
    </div>
    <!-- end auth-page-wrapper -->
    <!-- JAVASCRIPT -->
    <script src="~/velzon/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/velzon/assets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/velzon/assets/libs/node-waves/waves.min.js"></script>
    <script src="~/velzon/assets/libs/feather-icons/feather.min.js"></script>
    <script src="~/velzon/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
    <script src="~/velzon/assets/js/plugins.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script> 
    <script src="~/velzon/assets/js/app.js"></script>

    <!-- particles js -->
    <script src="~/velzon/assets/libs/particles.js/particles.js"></script>
    <!-- particles app js -->
    <script src="~/velzon/assets/js/pages/particles.app.js"></script>
    <!-- validation init -->
    <script src="~/velzon/assets/js/pages/form-validation.init.js"></script>


    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#üye_ol").click(function (event) {
                event.preventDefault();
                var formData = {
                    UserName: $("#UserName").val(),
                    UserEmail: $("#UserEmail").val(),
                    UserPassword: $("#UserPassword").val(),
                    PhoneNumber:$("#PhoneNumber").val()
                };

                $.ajax({
                    url: '/Signup/üyeOl',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(formData),
                    success: function (response) {
                        if (response.success) { 
                            Swal.fire({
                                icon: 'success',
                                title: 'Başarıyla Kayıt Oldunuz!',
                                text: response.message,
                                confirmButtonText: 'Tamam'
                            }).then(function() { 
                                window.location.href = '/Signin/Index';
                            });
                        } else { 
                            Swal.fire({
                                icon: 'error',
                                title: 'Kayıt Başarısız!',
                                text: response.message,
                                confirmButtonText: 'Tamam'
                            }).then(function() { 
                                window.location.href = '/Signup/Index';
                            });
                        }
                    },
                    error: function () { 
                        Swal.fire({
                            icon: 'error',
                            title: 'Bir Hata Oluştu',
                            text: 'Bir hata oluştu. Lütfen tekrar deneyin.',
                            confirmButtonText: 'Tamam'
                        }).then(function() { 
                            window.location.href = '/Signup/Index';
                        });
                    }
                });
            });
        });
    </script>

</body>
</html>